doktertani/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

app_name = 'doktertaniapp'


from django.urls import path
from doktertaniapp import views
from .views import detect, product
from django.views.generic import RedirectView
from doktertaniapp.viewset_api import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('sarancabai', CabaiViewset)
router.register('obat', ObatViewset)


urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    re_path(r'^$', views.home),
    re_path('predict/', include('doktertaniapp.urls')),
    re_path('bm/', include('predict_bawangm.urls')),
    path('', include('doktertaniapp.urls')),
    re_path(r'^option/$', detect),
    path('option/', RedirectView.as_view(url='/', permanent=True)),
    re_path(r'^product/$', product),
    path('product/', RedirectView.as_view(url='/', permanent=True)),
]

doktertaniapp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from doktertaniapp import views
from django.views.generic import RedirectView
from .views import detect
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^option/$', detect),
]

from django.urls import path
from doktertaniapp import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

predict_bawangm/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import RedirectView
from .views import detect
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^option/$', detect),
]

from django.urls import path
from predict_bawangm import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
]

doktertaniapp/models.py
# prediction/models.py

from django.db import models

class SaranCabai(models.Model):
    penyakit = models.CharField(max_length=100)
    gejala_umum = models.TextField()
    saran = models.TextField()
    obat = models.TextField()

    def __str__(self):
        return self.penyakit
    
class Obat(models.Model):
    obat = models.CharField(max_length=100)
    diskripsi = models.TextField()
    harga = models.TextField()

    def __str__(self):
        return self.penyakit


doktertaniapp/forms.py
# prediction/forms.py

from django import forms

class SymptomForm(forms.Form):
    symptoms = forms.MultipleChoiceField(
        choices=[],
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'horizontal-list', 'style': 'column-count: 3;'}),  # Atur jumlah kolom
        label='Pilih gejala (maksimal 5 gejala penyakit cabai)',
    )

    def __init__(self, *args, **kwargs):
        gejala_list = kwargs.pop('gejala_list', [])
        super(SymptomForm, self).__init__(*args, **kwargs)
        self.fields['symptoms'].choices = [(gejala, gejala) for gejala in gejala_list]

    def clean_symptoms(self):
        symptoms = self.cleaned_data.get('symptoms')
        if len(symptoms) > 5:
            raise forms.ValidationError("Anda hanya dapat memilih maksimal 5 gejala.")
        return symptoms

predict_bawangm/forms.py
# prediction/forms.py

from django import forms

class SymptomForm(forms.Form):
    symptoms = forms.MultipleChoiceField(
        choices=[],
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'horizontal-list', 'style': 'column-count: 3;'}),  # Atur jumlah kolom
        label='Pilih gejala (maksimal 5 gejala penyakit bawang merah)',
    )

    def __init__(self, *args, **kwargs):
        gejala_list = kwargs.pop('gejala_list', [])
        super(SymptomForm, self).__init__(*args, **kwargs)
        self.fields['symptoms'].choices = [(gejala, gejala) for gejala in gejala_list]

    def clean_symptoms(self):
        symptoms = self.cleaned_data.get('symptoms')
        if len(symptoms) > 5:
            raise forms.ValidationError("Anda hanya dapat memilih maksimal 5 gejala.")
        return symptoms

doktertani/views.py
from django.shortcuts import render


def detect(request):
    return render(request,'option.html')

def product(request):
    return render(request, 'product.html')

def home(request):
    return render(request, 'index.html')

doktertaniapp/views.py
from django.shortcuts import render

def detect(request):
    return render(request,'option.html')

def home(request):
    return render(request, 'index.html')

# prediction/views.py
from django.shortcuts import render
from django.conf import settings
import pickle
from .forms import SymptomForm
import os

# Load the models
with open(os.path.join(settings.BASE_DIR, 'static', 'ML', 'cabe_model_plant_conditions.pkl'), 'rb') as f:
    df_plant_conditions = pickle.load(f)

with open( os.path.join(settings.BASE_DIR, 'static', 'ML', 'cabe_model_diseases.pkl'), 'rb') as f:
    df_diseases = pickle.load(f)

with open(os.path.join(settings.BASE_DIR, 'static', 'ML', 'cabe_model_rules.pkl'), 'rb') as f:
    df_rules = pickle.load(f)

def predict_disease(symptoms):
    matching_conditions = set(df_plant_conditions[df_plant_conditions['gejala'].isin(symptoms)]['kode_gejala'])

    predicted_diseases = set()
    for index, row in df_rules.iterrows():
        condition_codes = row['condition_disease'][0]
        disease_code = row['condition_disease'][1]

        if set(condition_codes) == matching_conditions:
            predicted_diseases.add(disease_code)

    if predicted_diseases:
        return list(predicted_diseases)
    else:
        return ["Penyakit tidak ditemukan"]

# prediction/views.py

def index(request):
    gejala_list = df_plant_conditions['gejala'].tolist()

    if request.method == "POST":
        form = SymptomForm(request.POST, gejala_list=gejala_list)
        if form.is_valid():
            symptoms = form.cleaned_data['symptoms']
            predicted_diseases = predict_disease(symptoms)
            if predicted_diseases != ["Penyakit tidak ditemukan"]:
                diseases_names = df_diseases[df_diseases['kode_penyakit'].isin(predicted_diseases)]['penyakit'].tolist()
                return render(request, 'predict.html', {'form': form, 'prediksi_penyakit': diseases_names})
            else:
                return render(request, 'predict.html', {'form': form, 'prediksi_penyakit': predicted_diseases})
    else:
        form = SymptomForm(gejala_list=gejala_list)
    return render(request, 'predict.html', {'form': form, 'gejala_list': gejala_list})


predict_bawangm/views.py
from django.shortcuts import render


def detect(request):
    return render(request,'option.html')

def home(request):
    return render(request, 'index.html')

# prediction/views.py
from django.shortcuts import render
from django.conf import settings
import pickle
import pandas as pd
from predict_bawangm.forms import SymptomForm
import os

with open(os.path.join(settings.BASE_DIR, 'static', 'ML', 'bm_model_plant_conditions.pkl'), 'rb') as f:
    df_plant_conditions = pickle.load(f)

with open( os.path.join(settings.BASE_DIR, 'static', 'ML', 'bm_model_diseases.pkl'), 'rb') as f:
    df_diseases = pickle.load(f)

with open(os.path.join(settings.BASE_DIR, 'static', 'ML', 'bm_model_rules.pkl'), 'rb') as f:
    df_rules = pickle.load(f)

def predict_disease(symptoms):
    matching_conditions = set(df_plant_conditions[df_plant_conditions['gejala'].isin(symptoms)]['kode_gejala'])

    predicted_diseases = set()
    for index, row in df_rules.iterrows():
        condition_codes = row['condition_disease'][0]
        disease_code = row['condition_disease'][1]

        if set(condition_codes) == matching_conditions:
            predicted_diseases.add(disease_code)

    if predicted_diseases:
        return list(predicted_diseases)
    else:
        return ["Penyakit tidak ditemukan"]

# prediction/views.py

def index(request):
    gejala_list = df_plant_conditions['gejala'].tolist()

    if request.method == "POST":
        form = SymptomForm(request.POST, gejala_list=gejala_list)
        if form.is_valid():
            symptoms = form.cleaned_data['symptoms']
            predicted_diseases = predict_disease(symptoms)
            if predicted_diseases != ["Penyakit tidak ditemukan"]:
                diseases_names = df_diseases[df_diseases['kode_penyakit'].isin(predicted_diseases)]['penyakit'].tolist()
                return render(request, 'predict.html', {'form': form, 'prediksi_penyakit': diseases_names})
            else:
                return render(request, 'predict.html', {'form': form, 'prediksi_penyakit': predicted_diseases})
    else:
        form = SymptomForm(gejala_list=gejala_list)
    return render(request, 'predict.html', {'form': form, 'gejala_list': gejala_list})


doktertaniapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="../static/images/load3.gif" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="/"><img src="../static/images/logo.png" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item active">
                                 <a class="nav-link" href="index.html"> Home  </a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="option/">Predict</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="/product/">Products </a>
                              </li>
                              <li class="nav-item d_none">
                                 <a class="nav-link" href="/product/"><i class="fa fa-search" aria-hidden="true"></i></a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- banner -->
      <section class="banner_main">
         <div class="container">
            <div class="row">
               <div class="col-md-12 ">
                  <div class="text-bg">
                     <h1>APLIKASI DOKTERTANI</h1>
                     <p>Aplikasi untuk membantu petani atau pemilik tanaman dalam mengidentifikasi masalah yang sedang dihadapi oleh tanaman mereka melalui fitur diagnosis berdasarkan deskripsi gejala yang disediakan pengguna</p>
                     <a href="#">Discover</a>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!-- end banner -->
      <!-- three_box -->
      <div class="three_box">
         <div class="container">
            <div class="row">
               <div class="col-md-4">
                  <div class="box_text">
                     <figure><img src="../static/images/img1.jpg" alt="#"/></figure>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="box_text">
                     <figure><img src="../static/images/img2.jpg" alt="#"/></figure>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="box_text">
                     <figure><img src="../static/images/img3.jpg" alt="#"/></figure>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- three_box -->
      <!-- hottest -->
      <div  class="hottest">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-5">
                  <div class="titlepage">
                     <h2>Gunakan Apikasi ini untuk peningkatan kebutuhan Anda
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="hottest_box">
                     <p>
                        <strong>1. Pengelolaan Tanaman yang Lebih Efektif:</strong><br>
                        Petani akan dapat mengelola tanaman mereka dengan lebih efektif karena mereka dapat mengidentifikasi penyakit dengan cepat melalui aplikasi.  dan kualitas produksi.<br></br>

                        <strong>2. Peningkatan Produktivitas dan Pendapatan:</strong><br>
                        Dengan adanya akses terhadap solusi pengobatan yang tepat, petani dapat mengurangi kerugian produksi akibat serangan penyakit tanaman.<br></br>

                        <strong>3. Penghematan Biaya dan Waktu:</strong><br>
                        Petani akan dapat menghemat biaya produksi karena mereka hanya menggunakan obat-obatan atau pestisida yang sesuai dengan penyakit tanaman yang didiagnosis.<br></br>
                        
                        <strong>4. Peningkatan Pengetahuan dan Keahlian:</strong><br>
                        Dengan menggunakan aplikasi ini secara teratur, petani akan dapat meningkatkan pengetahuan dan keahlian mereka dalam mengenali penyakit tanaman dan cara mengobatinya.
                     </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
      </div>
      <!-- end hottest -->
      <!-- choose  section -->
      <div class="choose ">
         <div class="container">
            <div class="row">
               <div class="col-md-8">
                  <div class="titlepage">
                     <h2>About Us </h2>
                     <p>there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined  </p>
                  </div>
               </div>
            </div>
         </div>
         <div class="container-fluid">
            <div class="row d_flex">
               <div class="col-xl-7 col-lg-7 col-md-12 col-sm-12">
                  <div class="padding_with">
                     <div class="row">
                        <div class="col-md-6 padding_bottom">
                           <div class="choose_box">
                              <i><img src="../static/images/bayu.png" alt="#"/></i>
                              <div class="choose_text">
                                 <h3>Bayu Kurniawan</h3>
                                 <p>3322600019</p>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-6 padding_bottom">
                           <div class="choose_box">
                              <i><img src="../static/images/yusuf.png" alt="#"/></i>
                              <div class="choose_text">
                                 <h3>Muhammad Yusuf Rajabiyah</h3>
                                 <p>3322600020</p>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-6 padding_bottom2">
                           <div class="choose_box">
                              <i><img src="../static/images/zen.png" alt="#"/></i>
                              <div class="choose_text">
                                 <h3>Muhammad Fauzil Kazhim Zen</h3>
                                 <p>3322600008</p>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-6">
                           <div class="choose_box">
                              <i><img src="../static/images/ilmi.png" alt="#"/></i>
                              <div class="choose_text">
                                 <h3>Ida Ayu Made 'Ilmi</h3>
                                 <p>3322600002</p>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12">
                  <div class="choose_img">
                     <figure><img src="../static/images/logoDT2.jpg" alt="#"/></figure>
                  </div>
               </div>
            </div>
         </div>
         <div class="container">
            <div class="row">
               <div class="col-md-5">
                  <a class="read_more" href="#">Read More</a>
               </div>
            </div>
         </div>
      </div>
      </div>
      <!-- end choose  section -->
      </div>
{% endblock %}


doktertaniapp/templates/predict.html
{% extends 'base.html' %}
{% load static %}
{% csrf_token %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
<style>
    body {
        background: url("{% static 'images/Kebun 1.png' %}") no-repeat center center fixed;
        background-size: cover;
    }
</style>
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/load3.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->

      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="/"><img src="{% static 'images/logo.png' %}" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item">
                                 <a class="nav-link" href="/"> Home  </a>
                              </li>
                              <li class="nav-item active">
                                 <a class="nav-link" href="/option/">Predict</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="/product/">Products </a>
                              </li>
                              <li class="nav-item d_none">
                                 <a class="nav-link" href="/product/"><i class="fa fa-search" aria-hidden="true"></i></a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prediksi Penyakit Tumbuhan Cabe</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <style>
        /* Form Container Styling */
        .form-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 30px;
            background: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
            text-align: left;
            opacity: 0.9;
        }

        .form-container h1 {
            font-family: 'Rajdhani', sans-serif;
            margin-bottom: 20px;
            font-size: 28px;
            color: #333;
            text-align: center;
            font-weight: 700;
        }

        .form-container form {
            font-family: 'Rajdhani', sans-serif;
            display: flex;
            flex-direction: column;
            gap: 10px;
            align-items: center;
            font-weight: 600
        }

        #id_symptoms {
            display: grid;
            grid-template-columns: repeat(3, 4fr); /* Dua kolom dalam satu baris */
            gap: 10px; /* Jarak antar elemen */
        }

        .form-container form button {
            padding: 12px 25px;
            font-family: 'Rajdhani', sans-serif;
            background: black;
            border: none;
            color: #f4cb1e;
            font-size: 24px;
            border-radius: 5px;
            cursor: pointer;
            transition: background 0.3s;
            font-weight: bold;
        }

        .form-container form button:hover {
            background-color:#f4cb1e;
            color: black;
        }

        /* Result Container Styling */
        .result-container {
            margin-top: 30px;
            opacity: 0.9;
        }

        .result-container h2 {
            color: #333;
            font-family: 'Rajdhani', sans-serif;
            margin-bottom: 15px;
            font-size: 24px;
            font-weight: 600;
        }

        .result-container ul {
            list-style-type: none;
            padding: 0;
        }

        .result-container ul li {
            font-family: 'Rajdhani', sans-serif;
            font-weight: 600;
            background: #f8f9fa;
            margin: 5px 0;
            padding: 15px;
            border-radius: 5px;
            font-size: 20px;
            color: #333;
        }
        
        /* CSS untuk mengatur lebar modal */
        #resultModal .modal-dialog {
            max-width: 1000px; /* Lebar maksimum modal *//* Lebar modal (dapat disesuaikan) */
        }

        /* Penyesuaian teks pada modal jika lebih panjang */
        #resultModal .modal-body {
            max-height: 70vh;
            overflow-y: auto;
        }


    </style>
</head>
    <div class="form-container">
        <h1>Prediksi Penyakit Tumbuhan</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Prediksi</button>
        </form>
        {% if prediksi_penyakit %}
            <div class="result-container">
                <h2>Hasil Prediksi:</h2>
                <ul id="results">
                    <div id="results">
                        <template>
                            <li v-for="(penyakit,i) in prediksiPenyakit" :key="penyakit" >
                                    <button @click="getPenyakitId(penyakit)">
                                    <strong>[[ penyakit ]] 
                                    </strong>
                                    </button>
                            </li>
                        </template>      
                    </div>
                </ul>
            </div>
        {% endif %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="resultModal" tabindex="-1" aria-labelledby="resultModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="resultModalLabel">Hasil Prediksi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="modal-content"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        var app = new Vue({
            el: '#results',
            delimiters: ['[[', ']]'],
            data: {
                prediksiPenyakit: {{ prediksi_penyakit|safe }},
                hasil: {}
            },
            methods: {
            getPenyakitId(penyakit) {
                let url = 'http://127.0.0.1:8000/api/sarancabai/';
                fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        let found = data.find(item => item.penyakit === penyakit);
                        let modalContent = document.getElementById('modal-content');
                        modalContent.innerHTML = ''; // Clear existing content

                        if (found) {
                            // Add HTML formatted string
                            let img = document.createElement('img');
                            img.src = `{% static 'images/img_pred/' %}` + found.id + '.jpg';
                            img.style.width = '20%'; // Optional: Adjust the image size
                            modalContent.appendChild(img);

                            let htmlString = 
                                '<br><strong>Nama Penyakit: </strong>' + penyakit +'<br><br>'+
                                '<strong>Gejala Umum:</strong><br>'+found.gejala_umum.replace(/\n/g, '<br></br>')+'<br><br>'+
                                '<strong>Saran:</strong><br>' + found.saran.replace(/\n/g, '<br></br>') + '<br><br>'+
                                '<strong>Obat:</strong><br>'
                            ;
                            modalContent.innerHTML += htmlString;

                            // Add the text from found.obat using innerText
                            let obatText = document.createElement('span');
                            obatText.innerText = found.obat;
                            modalContent.appendChild(obatText);
                        } else {
                            modalContent.innerText = 'Error: ' + penyakit;
                        }

                        $('#resultModal').modal('show');
                    })
                    .catch(error => console.log(error));
            }
        }
        });
    </script>

    </div>


{% endblock %}